Neos:
  Form:
    presets:
      default:
        finisherPresets:
          'Wegmeister.DatabaseStorage:DatabaseStorageFinisher':
            implementationClassName: Wegmeister\DatabaseStorage\Finishers\DatabaseStorageFinisher
            options: {  }
  Neos:
    fusion:
      autoInclude:
        'Wegmeister.DatabaseStorage': true
    modules:
      databaseStorage:
        label: 'Wegmeister.DatabaseStorage:Main:storage.databaseStorage'
        controller: \Wegmeister\DatabaseStorage\Controller\DatabaseStorageController
        description: 'Wegmeister.DatabaseStorage:Main:storage.databaseStorageDescription'
        icon: icon-database
        privilegeTarget: 'Wegmeister.DatabaseStorage:Backend.DatabaseStorageViewer'

Wegmeister:
  DatabaseStorage:
    creator: 'die wegmeister gmbh'
    title: 'Database Export'
    subject: 'Database Export'
    datetimeFormat: 'Y-m-d H:i:s'
