Neos:
  Form:
    presets:
      default:
        finisherPresets:
          'Wegmeister.DatabaseStorage:DatabaseStorageFinisher':
            implementationClassName: WM\StarterKit\Finishers\DatabaseStorageFinisher
            options: {  }
  Neos:
    modules:
      databaseStorage:
        label: 'Database storage'
        controller: \Wegmeister\DatabaseStorage\Controller\DatabaseStorageController
        description: 'List database storage entries'
        icon: icon-database
        privilegeTarget: 'Wegmeister.DatabaseStorage:Backend.DatabaseStorageViewer'
